AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
    TracingEnabled: True
     

Resources:

  # customMessageTrigger:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: lambda-triggers/
  #     Handler: custom-message-trigger.lambdaHandler
  #     Runtime: nodejs18.x
  #     MemorySize: 2048
  #     FunctionName: custom-message-trigger-fn
  #     Environment:
  #       Variables:
  #         SMTP_SERVER: "email-smtp.ap-south-1.amazonaws.com" # SES SMTP endpoint for your region
  #         SMTP_PORT: "587" # Choose between 587 (TLS) or 465 (SSL)
  #         SMTP_USERNAME:  'AKIA6I5V74BH4FVKMWXG' # Stored securely
  #         SMTP_PASSWORD: 'BOTJJKasYVBEn7TRm5BAzwTLtSOS7JA2QJ/pSUAmVgNA' # Stored securely
  #         EMAIL_FROM: "no-reply@amura.ai" # Replace with a verified SES email
  #     Policies:
  #       - Version: "2012-10-17"
  #         Statement:
  #           - Effect: Allow
  #             Action:
  #               - kms:Decrypt
  #               - ssm:GetParameter
  #             Resource: "*"
  
  smsCustomMessageTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-triggers/
      Handler: sms-custom-message-trigger.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 2048
      FunctionName: sms-custom-message-trigger-fn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - ssm:GetParameter
              Resource: "*"

  amuraHealthSignup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-triggers/
      Handler: amuraHealthSignup.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 2048
      FunctionName: amuraHealthSignup
      Environment:
        Variables:
          REGION: "ap-south-1"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - ssm:GetParameter
                - cognito-idp:SignUp
              Resource: "*"
      Events:
        amuraHealthSignup:
          Type: Api
          Properties:
            Path: /amuraHealthSignup
            Method: post
            
  
  ConfirmationSignup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-triggers/
      Handler: ConfirmationSignup.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 2048
      FunctionName: ConfirmationSignup
      Environment:
        Variables:
          REGION: "ap-south-1"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - ssm:GetParameter
                - cognito-idp:SignUp
              Resource: "*"
      Events:
        ConfirmationSignup:
          Type: Api
          Properties:
            Path: /ConfirmationSignup
            Method: post
  verifySignup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-triggers/
      Handler: verifySignup.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 2048
      FunctionName: verifySignup
      Environment:
        Variables:
          REGION: "ap-south-1"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - ssm:GetParameter
                - cognito-idp:SignUp
              Resource: "*"
      Events:
        verifySignup:
          Type: Api
          Properties:
            Path: /verifySignup
            Method: post  
  CreatePassword:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-triggers/
      Handler: CreatePassword.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 2048
      FunctionName: CreatePassword
      Environment:
        Variables:
          REGION: "ap-south-1"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - ssm:GetParameter
                - cognito-idp:SignUp
              Resource: "*"
      Events:
        CreatePassword:
          Type: Api
          Properties:
            Path: /CreatePassword
            Method: post
  
  CreateUsername:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-triggers/
      Handler: CreateUsername.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 2048
      FunctionName: CreateUsername
      Environment:
        Variables:
          REGION: "ap-south-1"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - ssm:GetParameter
                - cognito-idp:SignUp
              Resource: "*"
      Events:
        CreateUsername:
          Type: Api
          Properties:
            Path: /CreateUsername
            Method: post

  ResendConfirmationCodeRequest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-triggers/
      Handler: ResendConfirmationCodeRequest.resendOtp
      Runtime: nodejs18.x
      MemorySize: 2048
      FunctionName: ResendConfirmationCodeRequest
      Environment:
        Variables:
          REGION: "ap-south-1"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - ssm:GetParameter
                - cognito-idp:SignUp
              Resource: "*"
      Events:
        ResendConfirmationCodeRequest:
          Type: Api
          Properties:
            Path: /ResendConfirmationCodeRequest
            Method: post
     
  
Outputs:
  CreateAuthChallenge:
    Description: The ID of the smsCustomMessageTrigger
    Value: !GetAtt smsCustomMessageTrigger.Arn

  amuraHealthSignupUrl:
    Description: URL for the amuraHealthSignup Lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/amuraHealthSignup"
  ConfirmationSignup:
    Description: URL for the ConfirmationSignup Lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ConfirmationSignup"
  verifySignup:
    Description: URL for the verifySignup Lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/verifySignup"
  ResendConfirmationCodeRequest:
    Description: URL for the ResendConfirmationCodeRequest Lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ResendConfirmationCodeRequest"
  CreatePassword: 
    Description: URL for the CreatePassword Lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/CreatePassword"
  CreateUsername: 
    Description: URL for the CreateUsername Lambda function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/CreateUsername"